name: Linting

on: pull_request

jobs:
  lint:
    name: Linting Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
          cache: "npm" # Speeds up the install

      - run: npm ci

      # Step 1: Check formatting
      - name: Check Prettier
        run: npm run lint:prettier:check

      # Step 2: Check code quality
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --max-warnings=0
